Elevate/Elevate/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('todo/', include("todo.urls")),
    path('subgoal/', include("subgoal.urls")),
    path('reminder/', include("reminder.urls")),
    path("__reload__/", include("django_browser_reload.urls"))
]

Elevate/reminder/urls.py
from django.urls import path
from . import views

app_name = "reminder"

urlpatterns = [
    path("", views.home, name="home"),
    path("add_reminder/", views.add_reminder, name="add_reminder"),
    path("delete_reminder/<int:reminder_id>/", views.delete_reminder, name="delete_reminder"),
    path("update_reminder/<int:reminder_id>/", views.update_reminder, name="update_reminder"),
]

Elevate/subgoal/urls.py
from django.urls import path
from . import views

app_name = "subgoal"

urlpatterns = [
    path("", views.home, name="home"),
    path("goal/<int:goal_id>/", views.subgoal, name="goal"),
    path("add_goal", views.add_goal, name="add_goal"),
    path("delete_goal/<int:goal_id>/", views.delete_goal, name="delete_goal"),
    path("add_subgoal/", views.add_subgoal, name="add_subgoal"),
    path("delete_subgoal/<int:subgoal_id>/", views.delete_subgoal, name="delete_subgoal"),
    path("update_subgoal/<int:subgoal_id>/", views.update_subgoal, name="update_subgoal"),
]

Elevate/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.home, name="home"),
    path("add-task/", views.add_task, name="add"),
    path("delete-task/<int:task_id>/", views.delete_task, name="delete")
]

Elevate/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("", views.home, name="home"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

Elevate/reminder/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Reminder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    date = models.DateTimeField()
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Elevate/reminder/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Reminder
from django.core.mail import send_mail
from django.utils import timezone

# Create your views here.
def home(request):
    reminders = Reminder.objects.filter(user=request.user).order_by('-created_at')

    return render(request, "reminder/home.html", {
        "reminders": reminders
    })

def add_reminder(request):
    if request.method == "POST":
        title = request.POST["title"]
        date = request.POST["date"]

        Reminder.objects.create(
            user=request.user,
            title=title,
            date=date,
            completed=False
            )
        return HttpResponseRedirect(reverse("reminder:home"))

    return render(request, "reminder/add_reminder.html")
    
def update_reminder(request, reminder_id):
    if request.method == "POST":
        reminder = Reminder.objects.get(user=request.user, id=reminder_id)
        
        reminder.date = request.POST["date"]
        reminder.completed = request.POST["completed"]
        reminder.save()

        return HttpResponseRedirect(reverse("reminder:home"))

    return render(request, "reminder/update_reminder.html", {
        "reminder_id": reminder_id
    })
    
def delete_reminder(request, reminder_id):
    if request.method == "POST":
        reminder = Reminder.objects.get(user=request.user, id=reminder_id)
        reminder.delete()
        return HttpResponseRedirect(reverse("reminder:home"))

Elevate/reminder/templates/reminder/Reminder.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ELEVATE WEB</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white">
    <div class="background-container">
        <div class="bg-dark"></div>
        <div class="bg-purple-1"></div>
        <div class="bg-purple-2"></div>
        <div class="bg-blue"></div>
    </div>
    <div class="header-wrapper">
        <div class="header">
            <div class="logo">
                <img src="Logo.svg" alt="Logo">
            </div>
            <div class="side-menu">
                <a href="https://google.com">
                    <button class="side-menu-item">To do list</button>
                </a>
                <a href="https://google.com">
                    <button class="side-menu-item">Subgoal</button>
                </a>
                <a href="https://google.com">
                    <button class="side-menu-item">Progress tracker</button>
                </a>
                <a href="https://google.com">
                    <button class="side-menu-item">Reminder</button>
                </a>
            </div>
            <div class = "header-end">
                <div class="log-out">
                    <a href="https://google.com">Log out</a>
                </div>
                <div class = "profile-img">
                    <img src="https://via.placeholder.com/65x65" alt="Profile Image">
                </div>
            </div>
        </div>
    </div>
    <div class="reminder-section">
        <h2 class="reminder-title">Reminder</h2>
    </div>
    <div class="search-bar">
        <input type="text" class="search-input" placeholder="Search...">
        <button class="search-button">Search</button>
    </div>
    <div class="card-container">
        <div class="card card-1">
            <div class="menu-item menu-item-1">
                <button class="menu-icon">
                    <img src="Circle_Black.svg" alt="Kuliah">
                </button>
                <div class="menu-text">
                    <div class="menu-title">Kuliah</div>
                    <div class="submenu-title">> TIMELINE LOMBA BC</div>
                    <div class="submenu-title">> Semester 3</div>
                </div>
            </div>
            <div class="menu-item menu-item-2">
                <button class="menu-icon">
                    <img src="Circle_Black.svg" alt="Kerja">
                </button>
                <div class="menu-text">Kerja</div>
            </div>
            <div class="menu-item menu-item-3">
                <button class="menu-icon">
                    <img src="Circle_Black.svg" alt="Fitness">
                </button>
                <div class="menu-text">Fitness</div>
            </div>
            <div class="menu-item menu-item-4">
                <button class="menu-icon">
                    <img src="Circle_Black.svg" alt="Home">
                </button>
                <div class="menu-text">Home</div>
            </div>
            <div class="menu-item menu-item-5">
                <button class="menu-icon">
                    <img src="Circle_Black.svg" alt="Tubes 1">
                </button>
                <div class="menu-text">Tubes 1</div>
            </div>
        </div>
        <div class="card card-2">
            <div class="kuliah-title">Kuliah</div>
            <div class="timeline-lomba-list">TIMELINE LOMBA BC</div>
            <div class="card card-timeline card-1">
                <div class="left">
                    <button class="menu-icon2">
                        <img src="Circle_Green.svg" alt="Fiksasi submission">
                    </button>
                    <div class="card-content">
                        <div class="card-title">Fiksasi submission</div>
                        <div class="card-date">Senin, 26/08/2024 08.00<br>D-2, H-12, M-30, S-58</div>
                    </div>
                </div>
            </div>
            <div class="card card-timeline card-2">
                <div class="left">
                    <button class="menu-icon2">
                        <img src="Circle_Green.svg" alt="Submission!">
                    </button>
                    <div class="card-content">
                        <div class="card-title">SUBMISSION!</div>
                        <div class="card-date">Selasa, 27/08/2024 18.00<br>D-3, H-12, M-30, S-58</div>
                    </div>
                </div>
            </div>
            <div class="down-arrow">
                <button class="icon-down"></button>
            </div>
        </div>
        <div class="card card-3">
            <div class="notes-title">Notes</div>
            <div class="notes-text">yang teliti file submissionnya jangan sampe salah</div>
        </div>
    </div>
    <div class="footer">
        <div class="footer-logo">ELEVATE</div>
        <div class="footer-text">2024 ELEVATE. ALL RIGHTS RESERVED</div>
        <div class="footer-link">Terms of Service</div>
        <div class="footer-link">Privacy Policy</div>
    </div>
  
</body>
</html>

Elevate/reminder/templates/reminder/add_reminder.html
{% extends "reminder/layout.html" %}


{% load static %}


{% block title %}
    Add Reminder
{% endblock%}


{% block css %}
    <link rel="stylesheet" href="{% static 'reminder/css/add_reminder.css' %}">
{% endblock %}


{% block content %}
    <div class="add-subgoal-container">
        <div class="add-subgoal-background">
            <p class="card-title">Add New Reminder</p>
            <form action="{% url 'reminder:add_reminder' %}" method="post" class="subgoal-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Reminder Title:</label>
                    <input type="text" id="title" name="title" required class="form-control">
                </div>
                <div class="form-group">
                    <label for="date">Date:</label>
                    <input type="date" id="date" name="date" required class="form-control">
                </div>
                <br>
                <br>
                <input type="submit" value="Add Reminder" class="add-button">
            </form>
        </div>
    </div>
{% endblock %}

Elevate/reminder/templates/reminder/home.html
{% extends "reminder/layout.html" %}


{% load static %}


{% block title %}
    Reminder
{% endblock%}


{% block css %}
    <link rel="stylesheet" href="{% static 'reminder/css/home.css' %}">
{% endblock %}


{% block content %}
    <div class="flex-container">
        <div class="reminder-container">
            <p class="title">Reminder</p>
            
            <form action="{% url 'reminder:add_reminder' %}">
                {% csrf_token %}
                <input type="submit" value="Add New Reminder" class="form-control form-button">
            </form>
            <br>
            <div class="reminder-items">
                {% for reminder in reminders %}
                    <a href="{% url 'reminder:update_reminder' reminder.id %}">
                        <div class="reminder-item-container" >
                            <div class="reminder-title">
                                {{ reminder.title }}
                            </div>
                            <div>
                                Reminder date: {{ reminder.date }}
                            </div>
                            <div>
                                Completion Status: {{ reminder.completed }}
                            </div>
                            <div>
                                Reminder created at: {{ reminder.created_at}}
                            </div>
                        </div>
                    </a>
                    <br>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
{% endblock %}

Elevate/reminder/templates/reminder/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'reminder/css/layout.css' %}">
    {% block css %}

    {% endblock %}
  </head>
  <body>

    <div class="container">
      <header class="header">
        <div class="header-content">
          <div class="logo-section">
            <a href="{% url 'user:home' %}">
                <img class="logo-img" src="{% static 'reminder/images/logo.png' %}" alt="Elevate Logo">
            </a>
          </div>
          <nav class="nav-links">
            <a href="{% url 'todo:home' %}" class="nav-link"><b>To Do List</b></a>
            <a href="{% url 'subgoal:home' %}" class="nav-link"><b>Progress Tracker</b></a>
            <a href="{% url 'subgoal:home' %}" class="nav-link"><b>Subgoal</b></a>
            <a href="{% url 'reminder:home' %}" class="nav-link"><b>Reminder</b></a>
          </nav>
          <div class="auth-links">
            <a href="{% url 'user:logout' %}" class="login-link">Logout</a>
            <a href="#" class="signup-link">{{ request.user.username }}</a>
          </div>
        </div>
      </header>
    </div>

    {% block content%}
    
    {% endblock %}

    <footer>
        <div class="footer-container">
            <div class="footer-logo-section">
                <img class="footer-logo-img" src="{% static 'reminder/images/logo_black.png' %}" alt="Elevate Logo" />
            </div>
            <p>&copy; 2024 ELEVATE. All rights reserved.</p>
            <div class="footer-links">
                <a href="#" class="footer-link">Terms of Service</a>
                <a href="#" class="footer-link">Privacy Policy</a>
            </div>
        </div>
    </footer>
  </body>
</html>

Elevate/reminder/templates/reminder/update_reminder.html
{% extends "reminder/layout.html" %}


{% load static %}


{% block title %}
    Update Reminder
{% endblock%}


{% block css %}
    <link rel="stylesheet" href="{% static 'reminder/css/update_reminder.css' %}">
{% endblock %}


{% block content %}
    <div class="add-subgoal-container">
        <div class="add-subgoal-background">
            <p class="card-title">Update Reminder</p>
            <form action="{% url 'reminder:update_reminder' reminder_id %}" method="post" class="subgoal-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="date">Date:</label>
                    <input type="date" id="date" name="date" required class="form-control">
                </div>
                <div class="form-group">
                    <label for="completed">Completion Status:</label>
                    <select id="completed" name="completed" class="form-control">
                        <option value=False>False</option>
                        <option value=True>True</option>
                    </select>
                </div>
                <br>
                <br>
                <input type="submit" value="Update Reminder" class="update-button">
            </form>

            <form action="{% url 'reminder:delete_reminder' reminder_id %}" method="post" class="subgoal-form">
                {% csrf_token %}
                <input type="submit" value="Delete Reminder" class="delete-button">
            </form>
        </div>
    </div>
{% endblock %}