Elevate/Elevate/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('todo/', include("todo.urls")),
    path('subgoal/', include("subgoal.urls")),
    path('reminder/', include("reminder.urls")),
    path("__reload__/", include("django_browser_reload.urls"))
]

Elevate/reminder/urls.py
from django.urls import path
from . import views

app_name = "reminder"

urlpatterns = [
    path("", views.home, name="home"),
    path("add_reminder/", views.add_reminder, name="add_reminder"),
    path("delete_reminder/<int:reminder_id>/", views.delete_reminder, name="delete_reminder"),
    path("update_reminder/<int:reminder_id>/", views.update_reminder, name="update_reminder"),
]

Elevate/subgoal/urls.py
from django.urls import path
from . import views

app_name = "subgoal"

urlpatterns = [
    path("", views.home, name="home"),
    path("goal/<int:goal_id>/", views.subgoal, name="goal"),
    path("add_goal", views.add_goal, name="add_goal"),
    path("delete_goal/<int:goal_id>/", views.delete_goal, name="delete_goal"),
    path("add_subgoal/", views.add_subgoal, name="add_subgoal"),
    path("delete_subgoal/<int:subgoal_id>/", views.delete_subgoal, name="delete_subgoal"),
    path("update_subgoal/<int:subgoal_id>/", views.update_subgoal, name="update_subgoal"),
]

Elevate/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.home, name="home"),
    path("add-task/", views.add_task, name="add"),
    path("delete-task/<int:task_id>/", views.delete_task, name="delete")
]

Elevate/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("", views.home, name="home"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

Elevate/todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tasks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)  
    created_at = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at'] 

Elevate/todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Tasks

# Create your views here.
def home(request):
    tasks = Tasks.objects.filter(user=request.user).order_by('-created_at')
    
    return render(request, "todo/home.html", {
        "tasks": tasks
    })

def add_task(request):
    if request.method == "POST":
        task = request.POST["task"]
        if task:
            Tasks.objects.create(user=request.user, title=task.capitalize())
    return HttpResponseRedirect(reverse("todo:home"))

def delete_task(request, task_id):
    if request.method == "POST":
        task = Tasks.objects.get(user=request.user, id=task_id)
        task.delete()
        return HttpResponseRedirect(reverse("todo:home"))

Elevate/todo/templates/todo/add.html
{% extends "todo/layout.html" %}


{% load static %}


{% block title %}
    Add Task
{% endblock%}


{% block css %}
    <link rel="stylesheet" href="{% static 'todo/css/add.css' %}">
{% endblock %}


{% block content %}
    
{% endblock %}

Elevate/todo/templates/todo/home.html
{% extends "todo/layout.html" %}


{% load static %}


{% block title %}
    To Do List
{% endblock%}


{% block css %}
    <link rel="stylesheet" href="{% static 'todo/css/home.css' %}">
{% endblock %}


{% block content %}
    <div class="flex-container">
        <div class="to-do-container">
            <p class="title">To Do List</p>
            
            <form action="{% url 'todo:add' %}" method="post">
                {% csrf_token %}
                <input type="text" name="task" placeholder="Add new task" class="form-input-field">
                <input type="submit" value="Add" class="form-button">
            </form>
            <br>

            {% for task in tasks %}
                <div class="task-list-container">
                    <div class="sub-task-list-container">
                        {{ task.title }}
                        <form action="{% url 'todo:delete' task.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Remove" class="remove-button">
                        </form>
                    </div>
                    <div>Task created at: {{ task.created_at }}</div>
                </div>
            {% endfor %}
            <br>
        </div>
    </div>
{% endblock %}

Elevate/todo/templates/todo/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'todo/css/layout.css' %}">
    {% block css %}

    {% endblock %}
  </head>
  <body>

    <div class="container">
      <header class="header">
        <div class="header-content">
          <div class="logo-section">
            <a href="{% url 'user:home' %}">
                <img class="logo-img" src="{% static 'todo/images/logo.png' %}" alt="Elevate Logo">
            </a>
          </div>
          <nav class="nav-links">
            <a href="{% url 'todo:home' %}" class="nav-link"><b>To Do List</b></a>
            <a href="{% url 'subgoal:home' %}" class="nav-link"><b>Progress Tracker</b></a>
            <a href="{% url 'subgoal:home' %}" class="nav-link"><b>Subgoal</b></a>
            <a href="{% url 'reminder:home' %}" class="nav-link"><b>Reminder</b></a>
          </nav>
          <div class="auth-links">
            <a href="{% url 'user:logout' %}" class="login-link">Logout</a>
            <a href="#" class="signup-link">{{ request.user.username }}</a>
          </div>
        </div>
      </header>
    </div>

    {% block content%}
    
    {% endblock %}

    <footer>
        <div class="footer-container">
            <div class="footer-logo-section">
                <img class="footer-logo-img" src="{% static 'todo/images/logo_black.png' %}" alt="Elevate Logo" />
            </div>
            <p>&copy; 2024 ELEVATE. All rights reserved.</p>
            <div class="footer-links">
                <a href="#" class="footer-link">Terms of Service</a>
                <a href="#" class="footer-link">Privacy Policy</a>
            </div>
        </div>
    </footer>
  </body>
</html>